const express=require('express')
const router=express.Router()

const auth=require('../middleware/auth')
const register=require('../controller/partner')
const login=require('../controller/partner')
const user=require('../controller/partner')
const logout=require('../controller/partner')
const resetpass=require('../controller/partner')
const payment=require('../controller/partner')
const sendmail=require('../controller/partner')
const claim=require('../controller/partner')
const myclaims=require('../controller/partner')
const icon=require('../controller/partner')
const messages=require('../controller/partner')
const earnings=require('../controller/partner')

router.post('/register',register)
router.post('/login',login)
router.get('/user', auth, user)
router.get('/logout', auth, logout)
router.post('/resetpass',auth, resetpass)
router.post('/create-checkout-session',payment)
router.post('/sendmail',sendmail)
router.post('/claim',claim)
router.post('/myclaims',myclaims)
router.post('/icon',icon)
router.get('/messages/:type',messages)
router.get('/earnings/:id',earnings)

module.exports = router;